#include "web_templates.h"
#include <string.h>

// Platform-independent HTML interface template
static const char web_interface_html[] =
    "<!DOCTYPE html>\n"
    "<html>\n"
    "<head>\n"
    "    <title>ESP32-CAM GenICam Control</title>\n"
    "    <meta charset=\"UTF-8\">\n"
    "    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n"
    "    <style>\n"
    "        body { font-family: Arial, sans-serif; margin: 20px; background-color: #f0f0f0; }\n"
    "        .container { max-width: 800px; margin: 0 auto; background: white; padding: 20px; border-radius: 10px; box-shadow: 0 2px 10px rgba(0,0,0,0.1); }\n"
    "        .header { text-align: center; color: #333; border-bottom: 2px solid #007acc; padding-bottom: 10px; margin-bottom: 20px; }\n"
    "        .section { margin-bottom: 20px; padding: 15px; border: 1px solid #ddd; border-radius: 5px; }\n"
    "        .control-group { margin-bottom: 15px; }\n"
    "        label { display: inline-block; width: 150px; font-weight: bold; color: #555; }\n"
    "        input[type=\"range\"] { width: 200px; margin: 0 10px; }\n"
    "        input[type=\"number\"] { width: 100px; padding: 5px; border: 1px solid #ccc; border-radius: 3px; }\n"
    "        select { width: 150px; padding: 5px; border: 1px solid #ccc; border-radius: 3px; }\n"
    "        button { background-color: #007acc; color: white; padding: 10px 20px; border: none; border-radius: 5px; cursor: pointer; margin: 5px; }\n"
    "        button:hover { background-color: #005a99; }\n"
    "        .status { padding: 10px; border-radius: 5px; margin-bottom: 10px; }\n"
    "        .status.success { background-color: #d4edda; color: #155724; border: 1px solid #c3e6cb; }\n"
    "        .status.error { background-color: #f8d7da; color: #721c24; border: 1px solid #f5c6cb; }\n"
    "        .value-display { display: inline-block; width: 60px; text-align: center; font-weight: bold; color: #007acc; }\n"
    "    </style>\n"
    "</head>\n"
    "<body>\n"
    "    <div class=\"container\">\n"
    "        <div class=\"header\">\n"
    "            <h1>🎥 ESP32-CAM GenICam Control</h1>\n"
    "            <p>Real-time camera parameter control interface</p>\n"
    "        </div>\n"
    "        \n"
    "        <div id=\"status\" class=\"status\" style=\"display: none;\"></div>\n"
    "        \n"
    "        <div class=\"section\">\n"
    "            <h3>📷 Camera Controls</h3>\n"
    "            <div class=\"control-group\">\n"
    "                <label>Exposure Time:</label>\n"
    "                <input type=\"range\" id=\"exposure\" min=\"1\" max=\"100000\" value=\"10000\" oninput=\"updateExposure()\">\n"
    "                <span class=\"value-display\" id=\"exposureValue\">10000</span> μs\n"
    "            </div>\n"
    "            <div class=\"control-group\">\n"
    "                <label>Gain:</label>\n"
    "                <input type=\"range\" id=\"gain\" min=\"0\" max=\"30\" value=\"0\" oninput=\"updateGain()\">\n"
    "                <span class=\"value-display\" id=\"gainValue\">0</span> dB\n"
    "            </div>\n"
    "            <div class=\"control-group\">\n"
    "                <label>Brightness:</label>\n"
    "                <input type=\"range\" id=\"brightness\" min=\"-2\" max=\"2\" value=\"0\" oninput=\"updateBrightness()\">\n"
    "                <span class=\"value-display\" id=\"brightnessValue\">0</span>\n"
    "            </div>\n"
    "            <div class=\"control-group\">\n"
    "                <label>Contrast:</label>\n"
    "                <input type=\"range\" id=\"contrast\" min=\"-2\" max=\"2\" value=\"0\" oninput=\"updateContrast()\">\n"
    "                <span class=\"value-display\" id=\"contrastValue\">0</span>\n"
    "            </div>\n"
    "            <div class=\"control-group\">\n"
    "                <label>Saturation:</label>\n"
    "                <input type=\"range\" id=\"saturation\" min=\"-2\" max=\"2\" value=\"0\" oninput=\"updateSaturation()\">\n"
    "                <span class=\"value-display\" id=\"saturationValue\">0</span>\n"
    "            </div>\n"
    "        </div>\n"
    "        \n"
    "        <div class=\"section\">\n"
    "            <h3>⚙️ Advanced Controls</h3>\n"
    "            <div class=\"control-group\">\n"
    "                <label>White Balance:</label>\n"
    "                <select id=\"whiteBalance\" onchange=\"updateWhiteBalance()\">\n"
    "                    <option value=\"0\">Off</option>\n"
    "                    <option value=\"1\" selected>Auto</option>\n"
    "                </select>\n"
    "            </div>\n"
    "            <div class=\"control-group\">\n"
    "                <label>Trigger Mode:</label>\n"
    "                <select id=\"triggerMode\" onchange=\"updateTriggerMode()\">\n"
    "                    <option value=\"0\" selected>Off (Free Running)</option>\n"
    "                    <option value=\"1\">On (Hardware)</option>\n"
    "                    <option value=\"2\">Software</option>\n"
    "                </select>\n"
    "            </div>\n"
    "        </div>\n"
    "        \n"
    "        <div class=\"section\">\n"
    "            <h3>🔧 Actions</h3>\n"
    "            <button onclick=\"loadCurrentSettings()\">📥 Load Current Settings</button>\n"
    "            <button onclick=\"resetToDefaults()\">🔄 Reset to Defaults</button>\n"
    "        </div>\n"
    "        \n"
    "        <div class=\"section\">\n"
    "            <h3>ℹ️ Current Status</h3>\n"
    "            <div id=\"cameraStatus\">Loading...</div>\n"
    "        </div>\n"
    "    </div>\n"
    "    \n"
    "    <script>\n"
    "        function showStatus(message, isError = false) {\n"
    "            const status = document.getElementById('status');\n"
    "            status.textContent = message;\n"
    "            status.className = 'status ' + (isError ? 'error' : 'success');\n"
    "            status.style.display = 'block';\n"
    "            setTimeout(() => { status.style.display = 'none'; }, 3000);\n"
    "        }\n"
    "        \n"
    "        function updateExposure() {\n"
    "            const value = document.getElementById('exposure').value;\n"
    "            document.getElementById('exposureValue').textContent = value;\n"
    "            updateParameter('exposure_time', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateGain() {\n"
    "            const value = document.getElementById('gain').value;\n"
    "            document.getElementById('gainValue').textContent = value;\n"
    "            updateParameter('gain', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateBrightness() {\n"
    "            const value = document.getElementById('brightness').value;\n"
    "            document.getElementById('brightnessValue').textContent = value;\n"
    "            updateParameter('brightness', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateContrast() {\n"
    "            const value = document.getElementById('contrast').value;\n"
    "            document.getElementById('contrastValue').textContent = value;\n"
    "            updateParameter('contrast', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateSaturation() {\n"
    "            const value = document.getElementById('saturation').value;\n"
    "            document.getElementById('saturationValue').textContent = value;\n"
    "            updateParameter('saturation', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateWhiteBalance() {\n"
    "            const value = document.getElementById('whiteBalance').value;\n"
    "            updateParameter('white_balance_mode', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateTriggerMode() {\n"
    "            const value = document.getElementById('triggerMode').value;\n"
    "            updateParameter('trigger_mode', parseInt(value));\n"
    "        }\n"
    "        \n"
    "        function updateParameter(param, value) {\n"
    "            fetch('/api/camera/control', {\n"
    "                method: 'POST',\n"
    "                headers: { 'Content-Type': 'application/json' },\n"
    "                body: JSON.stringify({ [param]: value })\n"
    "            })\n"
    "            .then(response => response.json())\n"
    "            .then(data => {\n"
    "                if (data.success) {\n"
    "                    showStatus('✅ ' + param.replace('_', ' ') + ' updated successfully');\n"
    "                } else {\n"
    "                    showStatus('❌ Failed to update ' + param.replace('_', ' '), true);\n"
    "                }\n"
    "            })\n"
    "            .catch(error => {\n"
    "                showStatus('❌ Network error: ' + error.message, true);\n"
    "            });\n"
    "        }\n"
    "        \n"
    "        function loadCurrentSettings() {\n"
    "            fetch('/api/camera/control')\n"
    "            .then(response => response.json())\n"
    "            .then(data => {\n"
    "                document.getElementById('exposure').value = data.exposure_time || 10000;\n"
    "                document.getElementById('exposureValue').textContent = data.exposure_time || 10000;\n"
    "                document.getElementById('gain').value = data.gain || 0;\n"
    "                document.getElementById('gainValue').textContent = data.gain || 0;\n"
    "                document.getElementById('brightness').value = data.brightness || 0;\n"
    "                document.getElementById('brightnessValue').textContent = data.brightness || 0;\n"
    "                document.getElementById('contrast').value = data.contrast || 0;\n"
    "                document.getElementById('contrastValue').textContent = data.contrast || 0;\n"
    "                document.getElementById('saturation').value = data.saturation || 0;\n"
    "                document.getElementById('saturationValue').textContent = data.saturation || 0;\n"
    "                document.getElementById('whiteBalance').value = data.white_balance_mode || 1;\n"
    "                document.getElementById('triggerMode').value = data.trigger_mode || 0;\n"
    "                showStatus('📥 Settings loaded from camera');\n"
    "            })\n"
    "            .catch(error => {\n"
    "                showStatus('❌ Failed to load settings: ' + error.message, true);\n"
    "            });\n"
    "        }\n"
    "        \n"
    "        function resetToDefaults() {\n"
    "            document.getElementById('exposure').value = 10000;\n"
    "            document.getElementById('exposureValue').textContent = '10000';\n"
    "            document.getElementById('gain').value = 0;\n"
    "            document.getElementById('gainValue').textContent = '0';\n"
    "            document.getElementById('brightness').value = 0;\n"
    "            document.getElementById('brightnessValue').textContent = '0';\n"
    "            document.getElementById('contrast').value = 0;\n"
    "            document.getElementById('contrastValue').textContent = '0';\n"
    "            document.getElementById('saturation').value = 0;\n"
    "            document.getElementById('saturationValue').textContent = '0';\n"
    "            document.getElementById('whiteBalance').value = 1;\n"
    "            document.getElementById('triggerMode').value = 0;\n"
    "            \n"
    "            // Apply all defaults\n"
    "            updateParameter('exposure_time', 10000);\n"
    "            updateParameter('gain', 0);\n"
    "            updateParameter('brightness', 0);\n"
    "            updateParameter('contrast', 0);\n"
    "            updateParameter('saturation', 0);\n"
    "            updateParameter('white_balance_mode', 1);\n"
    "            updateParameter('trigger_mode', 0);\n"
    "            showStatus('🔄 Reset to default settings');\n"
    "        }\n"
    "        \n"
    "        function updateCameraStatus() {\n"
    "            fetch('/api/camera/status')\n"
    "            .then(response => response.json())\n"
    "            .then(data => {\n"
    "                const status = document.getElementById('cameraStatus');\n"
    "                status.innerHTML = `\n"
    "                    <strong>Camera Type:</strong> ${data.real_camera ? 'ESP32-CAM Hardware' : 'Dummy Mode'}<br>\n"
    "                    <strong>Pixel Format:</strong> ${data.pixel_format_name}<br>\n"
    "                    <strong>Resolution:</strong> ${data.width} x ${data.height}<br>\n"
    "                    <strong>Max Payload:</strong> ${data.max_payload_size} bytes\n"
    "                `;\n"
    "            })\n"
    "            .catch(error => {\n"
    "                document.getElementById('cameraStatus').textContent = 'Failed to load status';\n"
    "            });\n"
    "        }\n"
    "        \n"
    "        // Load current settings and status on page load\n"
    "        window.onload = function() {\n"
    "            loadCurrentSettings();\n"
    "            updateCameraStatus();\n"
    "            // Update status every 5 seconds\n"
    "            setInterval(updateCameraStatus, 5000);\n"
    "        };\n"
    "    </script>\n"
    "</body>\n"
    "</html>";

// Platform-independent template access functions
const char* web_get_interface_html(void) {
    return web_interface_html;
}

size_t web_get_interface_html_size(void) {
    return strlen(web_interface_html);
}