#include "genicam_xml.h"

const uint8_t genicam_xml_data[] =
    "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
    "\n"
    "<RegisterDescription\n"
    "	ModelName=\"ESP32CAMGigE\"\n"
    "	VendorName=\"ESP32GenICam\"\n"
    "	StandardNameSpace=\"None\"\n"
    "	SchemaMajorVersion=\"1\"\n"
    "	SchemaMinorVersion=\"0\"\n"
    "	SchemaSubMinorVersion=\"1\"\n"
    "	MajorVersion=\"1\"\n"
    "	MinorVersion=\"0\"\n"
    "	SubMinorVersion=\"0\"\n"
    "	ToolTip=\"ESP32-CAM GenICam Compatible Camera\"\n"
    "	ProductGuid=\"0\"\n"
    "	VersionGuid=\"0\"\n"
    "	xmlns=\"http://www.genicam.org/GenApi/Version_1_0\"\n"
    "	xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
    "	xsi:schemaLocation=\"http://www.genicam.org/GenApi/Version_1_0 GenApiSchema.xsd\">\n"
    "\n"
    "	<Category Name=\"Root\" NameSpace=\"Standard\">\n"
    "		<pFeature>DeviceControl</pFeature>\n"
    "		<pFeature>ImageFormatControl</pFeature>\n"
    "		<pFeature>AcquisitionControl</pFeature>\n"
    "		<pFeature>TransportLayerControl</pFeature>\n"
    "	</Category>\n"
    "\n"
    "	<!-- Device Control -->\n"
    "\n"
    "	<Category Name=\"DeviceControl\" NameSpace=\"Standard\">\n"
    "		<pFeature>DeviceVendorName</pFeature>\n"
    "		<pFeature>DeviceModelName</pFeature>\n"
    "		<pFeature>DeviceID</pFeature>\n"
    "		<pFeature>DeviceVersion</pFeature>\n"
    "	</Category>\n"
    "\n"
    "	<StringReg Name=\"DeviceVendorName\" NameSpace=\"Standard\">\n"
    "		<DisplayName>Vendor Name</DisplayName>\n"
    "		<Address>0x48</Address>\n"
    "		<Length>32</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "	</StringReg>\n"
    "\n"
    "	<StringReg Name=\"DeviceModelName\" NameSpace=\"Standard\">\n"
    "		<DisplayName>Model Name</DisplayName>\n"
    "		<Address>0x68</Address>\n"
    "		<Length>32</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "	</StringReg>\n"
    "\n"
    "	<StringReg Name=\"DeviceID\" NameSpace=\"Standard\">\n"
    "		<DisplayName>Device ID</DisplayName>\n"
    "		<Address>0xd8</Address>\n"
    "		<Length>16</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "	</StringReg>\n"
    "\n"
    "	<StringReg Name=\"DeviceVersion\" NameSpace=\"Standard\">\n"
    "		<DisplayName>Device Version</DisplayName>\n"
    "		<Address>0x88</Address>\n"
    "		<Length>32</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "	</StringReg>\n"
    "\n"
    "	<!-- Image Format Control -->\n"
    "\n"
    "	<Category Name=\"ImageFormatControl\" NameSpace=\"Standard\">\n"
    "		<pFeature>Width</pFeature>\n"
    "		<pFeature>Height</pFeature>\n"
    "		<pFeature>SensorWidth</pFeature>\n"
    "		<pFeature>SensorHeight</pFeature>\n"
    "		<pFeature>PixelFormat</pFeature>\n"
    "		<pFeature>JpegQuality</pFeature>\n"
    "	</Category>\n"
    "\n"
    "	<Integer Name=\"Width\" NameSpace=\"Standard\">\n"
    "		<Description>Width of the image in pixels.</Description>\n"
    "		<Value>320</Value>\n"
    "		<Min>320</Min>\n"
    "		<Max>320</Max>\n"
    "	</Integer>\n"
    "\n"
    "	<Integer Name=\"Height\" NameSpace=\"Standard\">\n"
    "		<Description>Height of the image in pixels.</Description>\n"
    "		<Value>240</Value>\n"
    "		<Min>240</Min>\n"
    "		<Max>240</Max>\n"
    "	</Integer>\n"
    "\n"
    "	<Integer Name=\"SensorWidth\" NameSpace=\"Standard\">\n"
    "		<Description>Sensor width in pixels (alias to Width).</Description>\n"
    "		<pValue>Width</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<Integer Name=\"SensorHeight\" NameSpace=\"Standard\">\n"
    "		<Description>Sensor height in pixels (alias to Height).</Description>\n"
    "		<pValue>Height</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<Enumeration Name=\"PixelFormat\" NameSpace=\"Standard\">\n"
    "		<Description>Format of the pixels.</Description>\n"
    "		<EnumEntry Name=\"Mono8\">\n"
    "			<Description>Monochrome 8-bit</Description>\n"
    "			<Value>0x01080001</Value>\n"
    "		</EnumEntry>\n"
    "		<EnumEntry Name=\"RGB565Packed\">\n"
    "			<Description>RGB 5:6:5 Packed</Description>\n"
    "			<Value>0x02100005</Value>\n"
    "		</EnumEntry>\n"
    "		<EnumEntry Name=\"YUV422Packed\">\n"
    "			<Description>YUV 4:2:2 Packed</Description>\n"
    "			<Value>0x02100004</Value>\n"
    "		</EnumEntry>\n"
    "		<EnumEntry Name=\"RGB8Packed\">\n"
    "			<Description>RGB 8:8:8 Packed</Description>\n"
    "			<Value>0x02180014</Value>\n"
    "		</EnumEntry>\n"
    "		<EnumEntry Name=\"JPEG\">\n"
    "			<Description>JPEG compressed format</Description>\n"
    "			<Value>0x80000001</Value>\n"
    "		</EnumEntry>\n"
    "		<pValue>PixelFormatReg</pValue>\n"
    "	</Enumeration>\n"
    "\n"
    "	<IntReg Name=\"PixelFormatReg\" NameSpace=\"Standard\">\n"
    "		<Address>0x100C</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<IntReg Name=\"JpegQuality\" NameSpace=\"Standard\">\n"
    "		<Description>JPEG compression quality (0-63, lower is higher quality)</Description>\n"
    "		<Address>0x1024</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<!-- Acquisition Control -->\n"
    "\n"
    "	<Category Name=\"AcquisitionControl\" NameSpace=\"Standard\">\n"
    "		<pFeature>AcquisitionMode</pFeature>\n"
    "		<pFeature>AcquisitionStart</pFeature>\n"
    "		<pFeature>AcquisitionStop</pFeature>\n"
    "		<pFeature>AcquisitionFrameRateAbs</pFeature>\n"
    "	</Category>\n"
    "\n"
    "	<Enumeration Name=\"AcquisitionMode\" NameSpace=\"Standard\">\n"
    "		<Description>Sets the acquisition mode.</Description>\n"
    "		<EnumEntry Name=\"Continuous\">\n"
    "			<Description>Continuous acquisition</Description>\n"
    "			<Value>0</Value>\n"
    "		</EnumEntry>\n"
    "		<Value>0</Value>\n"
    "	</Enumeration>\n"
    "\n"
    "	<Command Name=\"AcquisitionStart\" NameSpace=\"Standard\">\n"
    "		<Description>Starts the acquisition.</Description>\n"
    "		<pValue>AcquisitionStartValue</pValue>\n"
    "		<CommandValue>1</CommandValue>\n"
    "	</Command>\n"
    "\n"
    "	<Command Name=\"AcquisitionStop\" NameSpace=\"Standard\">\n"
    "		<Description>Stops the acquisition.</Description>\n"
    "		<pValue>AcquisitionStopValue</pValue>\n"
    "		<CommandValue>1</CommandValue>\n"
    "	</Command>\n"
    "\n"
    "	<Integer Name=\"AcquisitionFrameRateAbs\" NameSpace=\"Standard\">\n"
    "		<Description>Acquisition frame rate in frames per second (alias to FrameRate).</Description>\n"
    "		<pValue>FrameRate</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<!-- Transport Layer Control -->\n"
    "\n"
    "	<Category Name=\"TransportLayerControl\" NameSpace=\"Standard\">\n"
    "		<pFeature>PayloadSize</pFeature>\n"
    "		<pFeature>GevSCPSPacketSize</pFeature>\n"
    "		<pFeature>GevSCPHostPort</pFeature>\n"
    "		<pFeature>GevStreamChannelCount</pFeature>\n"
    "		<pFeature>GevNumberOfNetworkInterfaces</pFeature>\n"
    "		<pFeature>ArvGevStreamChannelCount</pFeature>\n"
    "		<pFeature>ArvGevNumberOfNetworkInterfaces</pFeature>\n"
    "		<pFeature>ChunkModeActive</pFeature>\n"
    "		<pFeature>ChunkComponentSelector</pFeature>\n"
    "		<pFeature>ChunkPartIndex</pFeature>\n"
    "	</Category>\n"
    "\n"
    "	<IntReg Name=\"PayloadSize\" NameSpace=\"Standard\">\n"
    "		<Description>Size of the payload in bytes.</Description>\n"
    "		<Address>0x1020</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<Integer Name=\"GevSCPHostPort\" NameSpace=\"Standard\">\n"
    "		<Description>Host port for streaming channel.</Description>\n"
    "		<pValue>GevSCPHostPortReg</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<IntReg Name=\"GevSCPHostPortReg\" NameSpace=\"Standard\">\n"
    "		<Description>Host port register for streaming channel.</Description>\n"
    "		<Address>0x0D10</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<IntReg Name=\"GevSCPSPacketSizeReg\" NameSpace=\"Standard\">\n"
    "		<Description>GVSP packet size register.</Description>\n"
    "		<Address>0x0D14</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<Integer Name=\"GevSCPSPacketSize\" NameSpace=\"Standard\">\n"
    "		<Description>GVSP packet size in bytes.</Description>\n"
    "		<pValue>GevSCPSPacketSizeReg</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<IntReg Name=\"GevStreamChannelCountReg\" NameSpace=\"Standard\">\n"
    "		<Description>Number of stream channels supported.</Description>\n"
    "		<Address>0x0D00</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<Integer Name=\"GevStreamChannelCount\" NameSpace=\"Standard\">\n"
    "		<Description>Number of stream channels (always 1 for this device).</Description>\n"
    "		<pValue>GevStreamChannelCountReg</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<Integer Name=\"ArvGevStreamChannelCount\" NameSpace=\"Standard\">\n"
    "		<Description>Aravis-compatible stream channel count.</Description>\n"
    "		<pValue>GevStreamChannelCountReg</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<IntReg Name=\"GevNumberOfNetworkInterfacesReg\" NameSpace=\"Standard\">\n"
    "		<Description>Number of network interfaces.</Description>\n"
    "		<Address>0x0D04</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<Integer Name=\"GevNumberOfNetworkInterfaces\" NameSpace=\"Standard\">\n"
    "		<Description>Number of network interfaces (always 1 for this device).</Description>\n"
    "		<pValue>GevNumberOfNetworkInterfacesReg</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<Integer Name=\"ArvGevNumberOfNetworkInterfaces\" NameSpace=\"Standard\">\n"
    "		<Description>Aravis-compatible number of network interfaces.</Description>\n"
    "		<pValue>GevNumberOfNetworkInterfacesReg</pValue>\n"
    "	</Integer>\n"
    "\n"
    "	<!-- Multipart/Chunk Features -->\n"
    "\n"
    "	<Boolean Name=\"ChunkModeActive\" NameSpace=\"Standard\">\n"
    "		<Description>Enables multipart payload mode for streaming image data with metadata.</Description>\n"
    "		<pValue>ChunkModeActiveReg</pValue>\n"
    "	</Boolean>\n"
    "\n"
    "	<IntReg Name=\"ChunkModeActiveReg\" NameSpace=\"Standard\">\n"
    "		<Description>Register controlling multipart payload mode (bit 0).</Description>\n"
    "		<Address>0x0D24</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<Enumeration Name=\"ChunkComponentSelector\" NameSpace=\"Standard\">\n"
    "		<Description>Selects which component to configure in multipart mode.</Description>\n"
    "		<EnumEntry Name=\"Image\">\n"
    "			<Description>Image data component</Description>\n"
    "			<Value>0</Value>\n"
    "		</EnumEntry>\n"
    "		<EnumEntry Name=\"Metadata\">\n"
    "			<Description>Metadata component</Description>\n"
    "			<Value>1</Value>\n"
    "		</EnumEntry>\n"
    "		<Value>0</Value>\n"
    "	</Enumeration>\n"
    "\n"
    "	<Integer Name=\"ChunkPartIndex\" NameSpace=\"Standard\">\n"
    "		<Description>Index of the current component part in multipart payload.</Description>\n"
    "		<Value>0</Value>\n"
    "		<Min>0</Min>\n"
    "		<Max>15</Max>\n"
    "	</Integer>\n"
    "\n"
    "	<!-- Command Value Registers -->\n"
    "\n"
    "	<IntReg Name=\"AcquisitionStartValue\" NameSpace=\"Standard\">\n"
    "		<Description>Register for AcquisitionStart command.</Description>\n"
    "		<Address>0x1000</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>WO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<IntReg Name=\"AcquisitionStopValue\" NameSpace=\"Standard\">\n"
    "		<Description>Register for AcquisitionStop command.</Description>\n"
    "		<Address>0x1004</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>WO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<!-- Stream Control Registers -->\n"
    "\n"
    "	<IntReg Name=\"PacketDelay\" NameSpace=\"Standard\">\n"
    "		<Description>Inter-packet delay in microseconds.</Description>\n"
    "		<Address>0x1010</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<IntReg Name=\"FrameRate\" NameSpace=\"Standard\">\n"
    "		<Description>Frame rate in frames per second.</Description>\n"
    "		<Address>0x1014</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<IntReg Name=\"PacketSize\" NameSpace=\"Standard\">\n"
    "		<Description>GVSP data packet size in bytes.</Description>\n"
    "		<Address>0x1018</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RW</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<IntReg Name=\"StreamStatus\" NameSpace=\"Standard\">\n"
    "		<Description>Stream status register (bit 15 = error).</Description>\n"
    "		<Address>0x101C</Address>\n"
    "		<Length>4</Length>\n"
    "		<AccessMode>RO</AccessMode>\n"
    "		<pPort>Device</pPort>\n"
    "		<Sign>Unsigned</Sign>\n"
    "		<Endianess>BigEndian</Endianess>\n"
    "	</IntReg>\n"
    "\n"
    "	<!-- Port -->\n"
    "\n"
    "	<Port Name=\"Device\" NameSpace=\"Standard\">\n"
    "	</Port>\n"
    "\n"
    "</RegisterDescription>\n";

const size_t genicam_xml_size = sizeof(genicam_xml_data) - 1; // Exclude null terminator