#include "genicam_xml.h"

const char genicam_xml_data[] = 
"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n"
"\n"
"<RegisterDescription\n"
"	ModelName=\"ESP32CAMGigE\"\n"
"	VendorName=\"ESP32GenICam\"\n"
"	StandardNameSpace=\"None\"\n"
"	SchemaMajorVersion=\"1\"\n"
"	SchemaMinorVersion=\"0\"\n"
"	SchemaSubMinorVersion=\"1\"\n"
"	MajorVersion=\"1\"\n"
"	MinorVersion=\"0\"\n"
"	SubMinorVersion=\"0\"\n"
"	ToolTip=\"ESP32-CAM GenICam Compatible Camera\"\n"
"	ProductGuid=\"0\"\n"
"	VersionGuid=\"0\"\n"
"	xmlns=\"http://www.genicam.org/GenApi/Version_1_0\"\n"
"	xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"\n"
"	xsi:schemaLocation=\"http://www.genicam.org/GenApi/Version_1_0 GenApiSchema.xsd\">\n"
"\n"
"	<Category Name=\"Root\" NameSpace=\"Standard\">\n"
"		<pFeature>DeviceControl</pFeature>\n"
"		<pFeature>ImageFormatControl</pFeature>\n"
"		<pFeature>AcquisitionControl</pFeature>\n"
"		<pFeature>TransportLayerControl</pFeature>\n"
"	</Category>\n"
"\n"
"	<!-- Device Control -->\n"
"\n"
"	<Category Name=\"DeviceControl\" NameSpace=\"Standard\">\n"
"		<pFeature>DeviceVendorName</pFeature>\n"
"		<pFeature>DeviceModelName</pFeature>\n"
"		<pFeature>DeviceID</pFeature>\n"
"		<pFeature>DeviceVersion</pFeature>\n"
"	</Category>\n"
"\n"
"	<StringReg Name=\"DeviceVendorName\" NameSpace=\"Standard\">\n"
"		<DisplayName>Vendor Name</DisplayName>\n"
"		<Address>0x48</Address>\n"
"		<Length>32</Length>\n"
"		<AccessMode>RO</AccessMode>\n"
"		<pPort>Device</pPort>\n"
"	</StringReg>\n"
"\n"
"	<StringReg Name=\"DeviceModelName\" NameSpace=\"Standard\">\n"
"		<DisplayName>Model Name</DisplayName>\n"
"		<Address>0x68</Address>\n"
"		<Length>32</Length>\n"
"		<AccessMode>RO</AccessMode>\n"
"		<pPort>Device</pPort>\n"
"	</StringReg>\n"
"\n"
"	<StringReg Name=\"DeviceID\" NameSpace=\"Standard\">\n"
"		<DisplayName>Device ID</DisplayName>\n"
"		<Address>0xd8</Address>\n"
"		<Length>16</Length>\n"
"		<AccessMode>RO</AccessMode>\n"
"		<pPort>Device</pPort>\n"
"	</StringReg>\n"
"\n"
"	<StringReg Name=\"DeviceVersion\" NameSpace=\"Standard\">\n"
"		<DisplayName>Device Version</DisplayName>\n"
"		<Address>0x88</Address>\n"
"		<Length>32</Length>\n"
"		<AccessMode>RO</AccessMode>\n"
"		<pPort>Device</pPort>\n"
"	</StringReg>\n"
"\n"
"	<!-- Image Format Control -->\n"
"\n"
"	<Category Name=\"ImageFormatControl\" NameSpace=\"Standard\">\n"
"		<pFeature>Width</pFeature>\n"
"		<pFeature>Height</pFeature>\n"
"		<pFeature>PixelFormat</pFeature>\n"
"	</Category>\n"
"\n"
"	<Integer Name=\"Width\" NameSpace=\"Standard\">\n"
"		<Description>Width of the image in pixels.</Description>\n"
"		<Value>320</Value>\n"
"		<Min>320</Min>\n"
"		<Max>320</Max>\n"
"	</Integer>\n"
"\n"
"	<Integer Name=\"Height\" NameSpace=\"Standard\">\n"
"		<Description>Height of the image in pixels.</Description>\n"
"		<Value>240</Value>\n"
"		<Min>240</Min>\n"
"		<Max>240</Max>\n"
"	</Integer>\n"
"\n"
"	<Enumeration Name=\"PixelFormat\" NameSpace=\"Standard\">\n"
"		<Description>Format of the pixels.</Description>\n"
"		<EnumEntry Name=\"Mono8\">\n"
"			<Description>Monochrome 8-bit</Description>\n"
"			<Value>0x01080001</Value>\n"
"		</EnumEntry>\n"
"		<Value>0x01080001</Value>\n"
"	</Enumeration>\n"
"\n"
"	<!-- Acquisition Control -->\n"
"\n"
"	<Category Name=\"AcquisitionControl\" NameSpace=\"Standard\">\n"
"		<pFeature>AcquisitionMode</pFeature>\n"
"		<pFeature>AcquisitionStart</pFeature>\n"
"		<pFeature>AcquisitionStop</pFeature>\n"
"	</Category>\n"
"\n"
"	<Enumeration Name=\"AcquisitionMode\" NameSpace=\"Standard\">\n"
"		<Description>Sets the acquisition mode.</Description>\n"
"		<EnumEntry Name=\"Continuous\">\n"
"			<Description>Continuous acquisition</Description>\n"
"			<Value>0</Value>\n"
"		</EnumEntry>\n"
"		<Value>0</Value>\n"
"	</Enumeration>\n"
"\n"
"	<Command Name=\"AcquisitionStart\" NameSpace=\"Standard\">\n"
"		<Description>Starts the acquisition.</Description>\n"
"		<pValue>AcquisitionStartValue</pValue>\n"
"		<CommandValue>1</CommandValue>\n"
"	</Command>\n"
"\n"
"	<Command Name=\"AcquisitionStop\" NameSpace=\"Standard\">\n"
"		<Description>Stops the acquisition.</Description>\n"
"		<pValue>AcquisitionStopValue</pValue>\n"
"		<CommandValue>1</CommandValue>\n"
"	</Command>\n"
"\n"
"	<!-- Transport Layer Control -->\n"
"\n"
"	<Category Name=\"TransportLayerControl\" NameSpace=\"Standard\">\n"
"		<pFeature>PayloadSize</pFeature>\n"
"		<pFeature>GevSCPSPacketSize</pFeature>\n"
"		<pFeature>GevSCPHostPort</pFeature>\n"
"	</Category>\n"
"\n"
"	<Integer Name=\"PayloadSize\" NameSpace=\"Standard\">\n"
"		<Description>Size of the payload in bytes.</Description>\n"
"		<Value>76800</Value>\n"
"		<Min>76800</Min>\n"
"		<Max>76800</Max>\n"
"	</Integer>\n"
"\n"
"	<Integer Name=\"GevSCPSPacketSize\" NameSpace=\"Standard\">\n"
"		<Description>GVSP packet size in bytes.</Description>\n"
"		<Value>1500</Value>\n"
"		<Min>576</Min>\n"
"		<Max>1500</Max>\n"
"	</Integer>\n"
"\n"
"	<Integer Name=\"GevSCPHostPort\" NameSpace=\"Standard\">\n"
"		<Description>Host port for streaming channel.</Description>\n"
"		<Value>0</Value>\n"
"		<Min>0</Min>\n"
"		<Max>65535</Max>\n"
"	</Integer>\n"
"\n"
"	<!-- Command Value Registers -->\n"
"\n"
"	<Integer Name=\"AcquisitionStartValue\" NameSpace=\"Standard\">\n"
"		<Description>Register for AcquisitionStart command.</Description>\n"
"		<Value>1</Value>\n"
"		<Min>0</Min>\n"
"		<Max>1</Max>\n"
"	</Integer>\n"
"\n"
"	<Integer Name=\"AcquisitionStopValue\" NameSpace=\"Standard\">\n"
"		<Description>Register for AcquisitionStop command.</Description>\n"
"		<Value>1</Value>\n"
"		<Min>0</Min>\n"
"		<Max>1</Max>\n"
"	</Integer>\n"
"\n"
"	<!-- Port -->\n"
"\n"
"	<Port Name=\"Device\" NameSpace=\"Standard\">\n"
"	</Port>\n"
"\n"
"</RegisterDescription>\n";

const size_t genicam_xml_size = sizeof(genicam_xml_data) - 1; // Exclude null terminator